# Generated by Django 2.2.7 on 2020-04-26 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('author', models.CharField(max_length=260)),
                ('text', models.TextField(max_length=260)),
                ('create_date', models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 31, 14, 437881, tzinfo=utc))),
                ('posted_date', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=260)),
                ('text', models.TextField(max_length=260)),
                ('posted_date', models.TimeField(default=datetime.datetime(2020, 4, 26, 17, 31, 14, 438238, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='simple_app.Post')),
            ],
        ),
    ]
